export type Car = {
  id: string;
  make: string;
  model: string;
  modelId: number;
  year: number;
  fuel: "petrol" | "diesel" | "electric" | "hybrid";
  type: string;
  transmission: "Automatic" | "Manual";
  pricePerDay: number;
  image: string;
  mileage: number;
  seats: number;
  color: string;
  displacement: number;
  rating: number;
  isFeatured: boolean;
  features?: string[];
  location?: string;
};
