export type Car = {
  id: string;
  make: string;
  model: string;
  year: number;
  fuel: string;
  type: string;
  transmission: string;
  pricePerDay: number;
  image: string;
  mileage?: number;
  seats?: number;
  color?: string;
  engine?: number;
  location?: string;
  rating?: number;
  availability?: string;
  features?: string[];
  isFeatured?: boolean;
  status: string;
};
